[package]
name = "cloudy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
async-std = { version = "1.12.0", features = ["attributes"] }
async-recursion = "1.0.0"
